var AREAS = [{"id":"penal","es":{"n":"Penal","t":"Defensa y Justicia a tu Lado","s":"Representación efectiva en todas las etapas del proceso penal, en acusación o defensa.","f":"En VEXSTON, brindamos una asistencia robusta y experta en casos penales, respaldada por un equipo comprometido con la representación efectiva en todas las etapas del proceso penal, ya sea que formes parte de la acusación o la defensa. Nos dedicamos a defender tus derechos y garantías con un enfoque integral que incluye asesoramiento preventivo, correctivo y estratégico, aportando soluciones claras que te permitan afrontar el proceso legal con seguridad, confianza y tranquilidad."},"en":{"n":"Criminal Law","t":"Defense and Justice by Your Side","s":"Effective representation at every stage of the criminal process, in prosecution or defense.","f":"At VEXSTON, we provide robust, expert assistance in criminal cases, backed by a team committed to effective representation at every stage of the criminal process, whether you are part of the prosecution or the defense. We are dedicated to defending your rights and guarantees with a comprehensive approach that includes preventive, corrective and strategic counsel, delivering clear solutions that let you face the legal process with security, confidence and peace of mind."},"pt":{"n":"Direito Penal","t":"Defesa e Justiça ao Seu Lado","s":"Representação efetiva em todas as etapas do processo penal, na acusação ou na defesa.","f":"Na VEXSTON, oferecemos uma assistência robusta e especializada em casos penais, apoiada por uma equipe comprometida com a representação efetiva em todas as etapas do processo penal, seja você parte da acusação ou da defesa. Dedicamo-nos a defender seus direitos e garantias com uma abordagem integral que inclui assessoria preventiva, corretiva e estratégica, oferecendo soluções claras que permitem enfrentar o processo legal com segurança, confiança e tranquilidade."}},{"id":"civil","es":{"n":"Civil","t":"Salvaguarda en Asuntos Civiles","s":"Soluciones prácticas en materia contractual, patrimonial, sucesoral y de responsabilidad civil.","f":"Contamos con profesionales preparados para ayudar en todos los aspectos del derecho civil, con precisión, experticia y dedicación. Tanto en temas contractuales, de propiedad, patrimoniales, sucesiones, responsabilidad civil o cualquier otro ámbito relacionado, ponemos a tu disposición soluciones prácticas que resguarden esos intereses. Trabajamos para gerenciar procesos de manera justa y equilibrada, enfocándonos en la prevención de disputas, la resolución de conflictos, y en la atención de situaciones legales cotidianas y litigios."},"en":{"n":"Civil Law","t":"Safeguarding Your Civil Matters","s":"Practical solutions in contract, property, estate and civil-liability matters.","f":"We have professionals ready to help with every aspect of civil law, with precision, expertise and dedication. Whether in contractual, property, estate, succession, civil-liability matters or any other related area, we offer practical solutions that protect your interests. We work to manage processes fairly and evenly, focusing on preventing disputes, resolving conflicts, and handling everyday legal matters and litigation."},"pt":{"n":"Direito Civil","t":"Salvaguarda em Assuntos Civis","s":"Soluções práticas em matéria contratual, patrimonial, sucessória e de responsabilidade civil.","f":"Contamos com profissionais preparados para ajudar em todos os aspectos do direito civil, com precisão, experiência e dedicação. Seja em temas contratuais, patrimoniais, sucessórios, de responsabilidade civil ou qualquer outro âmbito relacionado, colocamos à sua disposição soluções práticas que resguardam esses interesses. Trabalhamos para gerenciar processos de forma justa e equilibrada, com foco na prevenção de disputas, na resolução de conflitos e no atendimento de questões legais cotidianas e litígios."}},{"id":"familia","es":{"n":"Familia","t":"Protegiendo lo que más Importa con Empatía","s":"Acompañamiento humano y especializado en divorcios, instituciones familiares y adopciones.","f":"En la firma entendemos que los asuntos familiares son más que simples trámites legales; son situaciones que tocan lo más profundo de las emociones y los valores personales. Por eso, en nuestra área de Derecho de Familia, no solo ofrecemos asesoría jurídica especializada, sino también un enfoque humano, solidario y empático. Brindamos acompañamiento en momentos sensibles, como divorcios, establecimiento de instituciones familiares, adopciones o cualquier otro tema relacionado con la familia, niños y adolescentes. Sabemos que cada caso es único y merece un trato personalizado, respetuoso y confidencial."},"en":{"n":"Family Law","t":"Protecting What Matters Most, With Empathy","s":"Human, specialized support through divorces, family arrangements and adoptions.","f":"At the firm, we understand that family matters are more than simple legal procedures; they touch the deepest emotions and personal values. That's why, in our Family Law practice, we offer not only specialized legal counsel but also a human, supportive and empathetic approach. We provide guidance in sensitive moments such as divorces, the establishment of family arrangements, adoptions or any other matter related to family, children and adolescents. We know that every case is unique and deserves personalized, respectful and confidential treatment."},"pt":{"n":"Direito de Família","t":"Protegendo o que Mais Importa, com Empatia","s":"Acompanhamento humano e especializado em divórcios, arranjos familiares e adoções.","f":"No escritório, entendemos que as questões familiares são mais do que simples trâmites legais; elas tocam o mais profundo das emoções e dos valores pessoais. Por isso, em nossa área de Direito de Família, oferecemos não apenas assessoria jurídica especializada, mas também uma abordagem humana, solidária e empática. Prestamos acompanhamento em momentos sensíveis, como divórcios, constituição de arranjos familiares, adoções ou qualquer outro tema relacionado à família, crianças e adolescentes. Sabemos que cada caso é único e merece um tratamento personalizado, respeitoso e confidencial."}},{"id":"corporativo","es":{"n":"Corporativo y Comercial","t":"Impulsando Sostenibilidad y Rendimiento","s":"Constitución de sociedades, contratos comerciales, fusiones y adquisiciones.","f":"Proveemos asesoría en derecho corporativo y comercial, abarcando la creación de entidades, manejo societario y la optimización jurídica de la gestión empresarial. Guiamos a los comerciantes y empresarios en la redacción de contratos comerciales, adecuación normativa y planificación fiscal; implementación de transacciones seguras y adherencia a la legislación vigente. También ofrecemos apoyo en fusiones y adquisiciones, así como la resolución de disputas. En situaciones de reestructuración y quiebras, proporcionamos estrategias para asegurar una transición adecuada. En VEXSTON, no solo somos tus asesores legales; somos tus aliados en el éxito empresarial."},"en":{"n":"Corporate & Commercial Law","t":"Driving Sustainability and Performance","s":"Company formation, commercial contracts, mergers and acquisitions.","f":"We provide corporate and commercial law counsel, covering entity formation, corporate governance and the legal optimization of business management. We guide merchants and business owners in drafting commercial contracts, regulatory compliance and tax planning; implementing secure transactions and adherence to current legislation. We also support mergers and acquisitions, as well as dispute resolution. In restructuring and bankruptcy situations, we provide strategies to ensure a proper transition. At VEXSTON, we are not just your legal advisors; we are your allies in business success."},"pt":{"n":"Direito Corporativo e Comercial","t":"Impulsionando Sustentabilidade e Desempenho","s":"Constituição de sociedades, contratos comerciais, fusões e aquisições.","f":"Prestamos assessoria em direito corporativo e comercial, abrangendo a criação de entidades, gestão societária e a otimização jurídica da gestão empresarial. Orientamos comerciantes e empresários na redação de contratos comerciais, adequação normativa e planejamento fiscal; implementação de transações seguras e cumprimento da legislação vigente. Também prestamos apoio em fusões e aquisições, bem como na resolução de disputas. Em situações de reestruturação e falência, oferecemos estratégias para assegurar uma transição adequada. Na VEXSTON, não somos apenas seus assessores jurídicos; somos seus aliados no sucesso empresarial."}},{"id":"laboral","es":{"n":"Laboral","t":"El Balance en las Relaciones Laborales","s":"Negociación colectiva, contratos, seguridad laboral y representación en demandas.","f":"En nuestra firma entendemos la importancia de ambientes laborales equitativos y productivos. Proveemos asesoría y representación en asuntos derivados de las relaciones laborales en sus distintos sujetos, individuales y colectivos, asegurando que los derechos de los intervinientes sean respetados y protegidos. Incluimos la negociación y redacción de contratos, gestión de negociaciones colectivas, asesoría en seguridad y salud en el trabajo, prevención y racionalización de estructuras salariales, reclamos extrajudiciales y representación en demandas judiciales, principalmente corporativas."},"en":{"n":"Labor Law","t":"Balance in Labor Relations","s":"Collective bargaining, contracts, workplace safety and litigation representation.","f":"At our firm we understand the importance of fair, productive work environments. We provide advisory and representation in matters arising from labor relations, both individual and collective, ensuring that the rights of all parties are respected and protected. This includes negotiating and drafting contracts, managing collective bargaining, occupational health and safety advisory, prevention and rationalization of salary structures, extrajudicial claims and representation in judicial proceedings, primarily corporate."},"pt":{"n":"Direito Trabalhista","t":"O Equilíbrio nas Relações Trabalhistas","s":"Negociação coletiva, contratos, segurança no trabalho e representação em processos.","f":"Em nosso escritório, entendemos a importância de ambientes de trabalho equitativos e produtivos. Prestamos assessoria e representação em assuntos decorrentes das relações trabalhistas, tanto individuais quanto coletivas, assegurando que os direitos dos envolvidos sejam respeitados e protegidos. Isso inclui a negociação e redação de contratos, gestão de negociações coletivas, assessoria em segurança e saúde no trabalho, prevenção e racionalização de estruturas salariais, reclamações extrajudiciais e representação em processos judiciais, principalmente corporativos."}},{"id":"compliance","es":{"n":"Compliance y Buen Gobierno","t":"Tu Aliado en la Integridad Empresarial","s":"Programas de cumplimiento normativo, auditorías y gobierno corporativo.","f":"En un entorno económico cada vez más regulado y competitivo, el cumplimiento normativo y el buen gobierno corporativo resultan esenciales para garantizar la integridad, transparencia y sostenibilidad de tu organización, e igualmente para evitar sanciones, multas y consecuencias legales. Trabajamos de la mano con tu organización para diseñar e implementar programas de cumplimiento adaptados a su sector y necesidades, así como para identificar y mitigar riesgos legales, regulatorios y reputacionales. También realizamos auditorías internas y revisiones de procesos."},"en":{"n":"Compliance & Corporate Governance","t":"Your Ally in Business Integrity","s":"Compliance programs, audits and corporate governance.","f":"In an increasingly regulated and competitive economic environment, regulatory compliance and good corporate governance are essential to guarantee your organization's integrity, transparency and sustainability, and to avoid sanctions, fines and legal consequences. We work hand in hand with your organization to design and implement compliance programs tailored to its sector and needs, as well as to identify and mitigate legal, regulatory and reputational risks. We also conduct internal audits and process reviews."},"pt":{"n":"Compliance e Governança Corporativa","t":"Seu Aliado na Integridade Empresarial","s":"Programas de compliance, auditorias e governança corporativa.","f":"Em um ambiente econômico cada vez mais regulado e competitivo, o cumprimento normativo e a boa governança corporativa são essenciais para garantir a integridade, transparência e sustentabilidade de sua organização, além de evitar sanções, multas e consequências legais. Trabalhamos em conjunto com sua organização para desenhar e implementar programas de compliance adaptados ao seu setor e necessidades, bem como para identificar e mitigar riscos legais, regulatórios e reputacionais. Também realizamos auditorias internas e revisões de processos."}},{"id":"constitucional","es":{"n":"Constitucional","t":"Apoyo Sobre Pilares Constitucionales","s":"Amparos, habeas data, habeas corpus y litigios ante el Tribunal Supremo de Justicia.","f":"Nos comprometemos a accionar en la protección de tus derechos fundamentales. Nuestros especialistas están capacitados para apoyar en la interpretación y aplicación de la Constitución, defendiendo tus derechos civiles, sociales y políticos con la máxima rigurosidad y profesionalismo. Ofrecemos representación en demandas de inconstitucionalidad, acciones de amparo de garantías constitucionales, habeas data, habeas corpus y litigios ante el Tribunal Supremo de Justicia y otros órganos jurisdiccionales."},"en":{"n":"Constitutional Law","t":"Support on Constitutional Pillars","s":"Constitutional relief actions, habeas data, habeas corpus and litigation before the Supreme Court.","f":"We are committed to acting in the protection of your fundamental rights. Our specialists are equipped to assist with the interpretation and application of the Constitution, defending your civil, social and political rights with the utmost rigor and professionalism. We offer representation in unconstitutionality claims, constitutional relief actions (amparo), habeas data, habeas corpus, and litigation before the Supreme Court of Justice and other jurisdictional bodies."},"pt":{"n":"Direito Constitucional","t":"Apoio Sobre os Pilares Constitucionais","s":"Ações de amparo, habeas data, habeas corpus e litígios perante o Supremo Tribunal.","f":"Comprometemo-nos a atuar na proteção de seus direitos fundamentais. Nossos especialistas estão capacitados para apoiar na interpretação e aplicação da Constituição, defendendo seus direitos civis, sociais e políticos com o máximo rigor e profissionalismo. Oferecemos representação em ações de inconstitucionalidade, ações de amparo de garantias constitucionais, habeas data, habeas corpus e litígios perante o Supremo Tribunal de Justiça e outros órgãos jurisdicionais."}},{"id":"inmobiliario","es":{"n":"Inmobiliario y Registral","t":"Soluciones para tus Transacciones Inmobiliarias","s":"Trámites de compra, venta y gestión de propiedades, sin contratiempos.","f":"Te acompañamos en cada etapa de tus transacciones inmobiliarias, ya sea que estés comprando, vendiendo o gestionando propiedades. Manejamos todos los trámites y procedimientos concernientes a bienes raíces, previniendo y resolviendo cualquier disputa, asegurando que cada paso se realice de manera legal y sin contratiempos, racionalizando las gestiones."},"en":{"n":"Real Estate & Registry Law","t":"Solutions for Your Real Estate Transactions","s":"Support through purchase, sale and property management transactions, hassle-free.","f":"We accompany you through every stage of your real estate transactions, whether you are buying, selling or managing properties. We handle all procedures related to real estate, preventing and resolving any dispute, ensuring that every step is carried out legally and without setbacks, streamlining the process."},"pt":{"n":"Direito Imobiliário e Registral","t":"Soluções para Suas Transações Imobiliárias","s":"Acompanhamento em compra, venda e gestão de imóveis, sem contratempos.","f":"Acompanhamos você em cada etapa de suas transações imobiliárias, seja comprando, vendendo ou gerenciando propriedades. Cuidamos de todos os trâmites e procedimentos relativos a bens imóveis, prevenindo e resolvendo qualquer disputa, garantindo que cada etapa seja realizada de forma legal e sem contratempos, racionalizando as gestões."}},{"id":"propiedad-intelectual","es":{"n":"Propiedad Intelectual","t":"Protección Universal para tus Ideas e Invenciones","s":"Registro y defensa de marcas, patentes, derechos de autor y franquicias.","f":"Reconocemos la importancia de las ideas, creaciones e invenciones. En derecho de propiedad intelectual apoyamos en el registro y defensa de derechos sobre marcas, patentes, derechos de autor, secretos comerciales, franquicias y diseños industriales, al igual que representación en los procedimientos administrativos en defensa de tus pretensiones como empresario o emprendedor, permitiéndote concentrarte en el desarrollo, la innovación y el éxito de tus proyectos."},"en":{"n":"Intellectual Property","t":"Universal Protection for Your Ideas and Inventions","s":"Registration and defense of trademarks, patents, copyrights and franchises.","f":"We recognize the importance of ideas, creations and inventions. In intellectual property, we support the registration and defense of rights over trademarks, patents, copyrights, trade secrets, franchises and industrial designs, as well as representation in administrative proceedings defending your interests as a business owner or entrepreneur, allowing you to focus on the development, innovation and success of your projects."},"pt":{"n":"Propriedade Intelectual","t":"Proteção Universal para Suas Ideias e Invenções","s":"Registro e defesa de marcas, patentes, direitos autorais e franquias.","f":"Reconhecemos a importância das ideias, criações e invenções. Em propriedade intelectual, apoiamos o registro e a defesa de direitos sobre marcas, patentes, direitos autorais, segredos comerciais, franquias e desenhos industriais, além de representação em procedimentos administrativos na defesa de suas pretensões como empresário ou empreendedor, permitindo que você se concentre no desenvolvimento, na inovação e no sucesso de seus projetos."}},{"id":"tributario","es":{"n":"Tributario","t":"Asesoría Fiscal para un Futuro Planificado","s":"Planificación fiscal, defensa en auditorías y resolución de conflictos tributarios.","f":"Sabemos que una correcta gestión fiscal es crucial para el éxito financiero. En VEXSTON ofrecemos acompañamiento integral en derecho tributario, con énfasis en planificación fiscal estratégica, asesoramiento en materia de impuestos y optimización de la carga fiscal. Asistimos en la interpretación y aplicación de normativas fiscales, la defensa en auditorías y procedimientos ante la administración tributaria, la resolución de conflictos tributarios y la interposición y trámite de recursos judiciales."},"en":{"n":"Tax Law","t":"Fiscal Advisory for a Planned Future","s":"Tax planning, defense in audits and resolution of tax disputes.","f":"We know that sound fiscal management is crucial to financial success. At VEXSTON we provide comprehensive tax-law support, with an emphasis on strategic tax planning, tax advisory and optimization of your tax burden. We assist with the interpretation and application of tax regulations, defense in audits and proceedings before the tax administration, resolution of tax disputes, and the filing and handling of judicial appeals."},"pt":{"n":"Direito Tributário","t":"Assessoria Fiscal para um Futuro Planejado","s":"Planejamento fiscal, defesa em fiscalizações e resolução de disputas tributárias.","f":"Sabemos que uma correta gestão fiscal é crucial para o sucesso financeiro. Na VEXSTON, oferecemos acompanhamento integral em direito tributário, com ênfase em planejamento fiscal estratégico, assessoria em matéria de impostos e otimização da carga tributária. Auxiliamos na interpretação e aplicação de normas fiscais, na defesa em fiscalizações e procedimentos perante a administração tributária, na resolução de disputas tributárias e na interposição e tramitação de recursos judiciais."}},{"id":"administrativo","es":{"n":"Administrativo","t":"Un Enlace Directo con la Administración Pública","s":"Recursos administrativos, contrataciones públicas y controversias ante entes oficiales.","f":"Navegar por el mundo de la Administración Pública puede ser complejo; no obstante, la experiencia del equipo de VEXSTON te facilita el proceso. Te representamos y proporcionamos estrategias de resolución de conflictos ante entes gubernamentales, lo cual incluye la gestión de recursos administrativos y judiciales. Trazamos una ruta segura en las contrataciones públicas y en los diversos trámites y controversias que puedan surgir ante los despachos oficiales."},"en":{"n":"Administrative Law","t":"A Direct Link to Public Administration","s":"Administrative appeals, public procurement and disputes before government bodies.","f":"Navigating the world of Public Administration can be complex; however, the experience of the VEXSTON team makes the process easier for you. We represent you and provide dispute-resolution strategies before government bodies, including the management of administrative and judicial appeals. We chart a secure path through public procurement and the various procedures and disputes that may arise before official agencies."},"pt":{"n":"Direito Administrativo","t":"Uma Ligação Direta com a Administração Pública","s":"Recursos administrativos, contratações públicas e disputas perante órgãos governamentais.","f":"Navegar pelo mundo da Administração Pública pode ser complexo; no entanto, a experiência da equipe da VEXSTON facilita o processo para você. Representamos você e fornecemos estratégias de resolução de conflitos perante entes governamentais, o que inclui a gestão de recursos administrativos e judiciais. Traçamos um caminho seguro nas contratações públicas e nos diversos trâmites e controvérsias que possam surgir perante os órgãos oficiais."}},{"id":"internacional","es":{"n":"Internacional","t":"Asesoría Legal Globalizada","s":"Contratos y operaciones transnacionales con cumplimiento multijurisdiccional.","f":"Disponemos de un equipo de especialistas preparados para guiarte a través de las complejidades de las relaciones legales entre países y entidades transnacionales. Ya sea en la elaboración y revisión de contratos internacionales o en el desarrollo de distintas operaciones y negocios, aseguramos el cumplimiento de normativas y estándares en diversas jurisdicciones. Aplicamos estrategias que incluyen el análisis de riesgos legales en mercados internacionales y el desarrollo de métodos para facilitar tu expansión comercial."},"en":{"n":"International Law","t":"Globalized Legal Advisory","s":"Cross-border contracts and transactions with multi-jurisdictional compliance.","f":"We have a team of specialists ready to guide you through the complexities of legal relations between countries and transnational entities. Whether in drafting and reviewing international contracts or developing various operations and business deals, we ensure compliance with regulations and standards across multiple jurisdictions. We apply strategies that include legal-risk analysis in international markets and the development of methods to facilitate your business expansion."},"pt":{"n":"Direito Internacional","t":"Assessoria Jurídica Globalizada","s":"Contratos e operações transnacionais com conformidade multijurisdicional.","f":"Contamos com uma equipe de especialistas prontos para guiá-lo pelas complexidades das relações jurídicas entre países e entidades transnacionais. Seja na elaboração e revisão de contratos internacionais ou no desenvolvimento de diversas operações e negócios, garantimos o cumprimento de normas e padrões em diversas jurisdições. Aplicamos estratégias que incluem a análise de riscos jurídicos em mercados internacionais e o desenvolvimento de métodos para facilitar sua expansão comercial."}},{"id":"hidrocarburos","es":{"n":"Hidrocarburos y Energía","t":"Acuerdos y Transacciones en Proyectos Energéticos","s":"Negociación de contratos y estrategias comerciales para la industria energética.","f":"Un equipo de expertos multidisciplinario está listo para ofrecerte un respaldo legal y comercial sólido, apoyándote para afrontar los escenarios cotidianos y capitalizar las oportunidades en la industria de hidrocarburos y energía. Nos especializamos en la negociación y redacción de contratos, acuerdos de comercialización, suministro y distribución, alineados a tus objetivos. Además, facilitamos asesoramiento y estrategias de comercialización, permitiendo maximizar el valor de tus productos y servicios en el mercado."},"en":{"n":"Oil, Gas & Energy","t":"Driving Agreements and Deals in Energy Projects","s":"Contract negotiation and commercial strategy for the energy industry.","f":"A multidisciplinary team of experts is ready to provide solid legal and commercial backing, helping you navigate everyday scenarios and capitalize on opportunities in the oil, gas and energy industry. We specialize in negotiating and drafting contracts, commercialization, supply and distribution agreements, aligned with your objectives. We also facilitate advisory and commercialization strategies, allowing you to maximize the value of your products and services in the market."},"pt":{"n":"Hidrocarbonetos e Energia","t":"Impulsionando Acordos e Transações em Projetos Energéticos","s":"Negociação de contratos e estratégias comerciais para a indústria de energia.","f":"Uma equipe multidisciplinar de especialistas está pronta para oferecer um respaldo jurídico e comercial sólido, apoiando você a enfrentar os cenários cotidianos e capitalizar as oportunidades na indústria de hidrocarbonetos e energia. Somos especializados na negociação e redação de contratos, acordos de comercialização, fornecimento e distribuição, alinhados aos seus objetivos. Além disso, facilitamos assessoria e estratégias de comercialização, permitindo maximizar o valor de seus produtos e serviços no mercado."}},{"id":"ambiental","es":{"n":"Ambiental","t":"Por un Futuro Sustentable","s":"Evaluación de impacto ambiental, permisos y cumplimiento normativo.","f":"Con VEXSTON cuentas con un soporte jurídico sólido para avanzar hacia un futuro sostenible, respetando el equilibrio de las economías de escala con la sustentabilidad del planeta y las buenas prácticas ambientales, a través de la asesoría integral a organizaciones y particulares. Prestamos asesoría en la evaluación de estudios de impactos ambientales, la aplicación de permisos y el cumplimiento normativo."},"en":{"n":"Environmental Law","t":"For a Sustainable Future","s":"Environmental impact assessments, permitting and regulatory compliance.","f":"With VEXSTON, you have solid legal support to move toward a sustainable future, balancing economies of scale with the planet's sustainability and good environmental practices, through comprehensive advisory to organizations and individuals. We provide advisory on environmental impact assessments, permit applications and regulatory compliance."},"pt":{"n":"Direito Ambiental","t":"Por um Futuro Sustentável","s":"Avaliação de impacto ambiental, licenciamento e conformidade regulatória.","f":"Com a VEXSTON, você conta com um respaldo jurídico sólido para avançar rumo a um futuro sustentável, equilibrando as economias de escala com a sustentabilidade do planeta e as boas práticas ambientais, por meio de assessoria integral a organizações e particulares. Prestamos assessoria na avaliação de estudos de impacto ambiental, na aplicação de licenças e no cumprimento normativo."}},{"id":"deportivo","es":{"n":"Deportivo","t":"Pasión y Experiencia en Cada Jugada","s":"Contratos, derechos de imagen, patrocinio y procedimientos disciplinarios deportivos.","f":"En Derecho Deportivo abarcamos desde la negociación y redacción de contratos, hasta la gestión de derechos de imagen y patrocinio. Nuestros expertos también están preparados para asesorar en la resolución de conflictos y la regulación de competiciones. Nuestra representación jurídica cubre la defensa de los intereses de clubes y sus integrantes en todas las áreas, incluyendo procedimientos disciplinarios deportivos y asuntos legales cotidianos."},"en":{"n":"Sports Law","t":"Passion and Experience in Every Play","s":"Contracts, image rights, sponsorship and sports disciplinary proceedings.","f":"In Sports Law we cover everything from negotiating and drafting contracts to managing image rights and sponsorships. Our experts are also prepared to advise on dispute resolution and competition regulation. Our legal representation covers the defense of the interests of clubs and their members across all areas, including sports disciplinary proceedings and everyday legal matters."},"pt":{"n":"Direito Desportivo","t":"Paixão e Experiência em Cada Jogada","s":"Contratos, direitos de imagem, patrocínio e processos disciplinares desportivos.","f":"Em Direito Desportivo, abrangemos desde a negociação e redação de contratos até a gestão de direitos de imagem e patrocínio. Nossos especialistas também estão preparados para assessorar na resolução de conflitos e na regulamentação de competições. Nossa representação jurídica cobre a defesa dos interesses de clubes e seus integrantes em todas as áreas, incluindo processos disciplinares desportivos e assuntos jurídicos cotidianos."}},{"id":"agrario","es":{"n":"Agrario","t":"Compartimos Nuestra Experiencia con tu Arraigo en la Actividad Productiva","s":"Adquisición y gestión de tierras, normativa agraria y conflictos entre particulares.","f":"El sector agrario es un pilar fundamental para la economía y la seguridad alimentaria. Unimos experiencia y conocimientos para la mejor asesoría en la adquisición y gestión de tierras, el cumplimiento de las normativas agrarias y medioambientales, la asistencia en procesos administrativos, recursos contenciosos, amparos agrarios y conflictos o litigios entre particulares, acuerdos de suministro agrícola y el soporte legal para el crecimiento sostenible de las actividades de este segmento."},"en":{"n":"Agrarian Law","t":"Sharing Our Expertise, Rooted in Your Productive Activity","s":"Land acquisition and management, agrarian regulations and disputes between private parties.","f":"The agrarian sector is a fundamental pillar for the economy and food security. We combine experience and knowledge to provide the best advisory on land acquisition and management, compliance with agrarian and environmental regulations, assistance in administrative proceedings, contentious appeals, agrarian relief actions and disputes or litigation between private parties, agricultural supply agreements, and the legal support needed for the sustainable growth of activities in this sector."},"pt":{"n":"Direito Agrário","t":"Compartilhando Nossa Experiência com Sua Atividade Produtiva","s":"Aquisição e gestão de terras, normas agrárias e conflitos entre particulares.","f":"O setor agrário é um pilar fundamental para a economia e a segurança alimentar. Unimos experiência e conhecimento para oferecer a melhor assessoria na aquisição e gestão de terras, no cumprimento das normas agrárias e ambientais, na assistência em processos administrativos, recursos contenciosos, ações de amparo agrário e conflitos ou litígios entre particulares, acordos de fornecimento agrícola, e o suporte jurídico necessário para o crescimento sustentável das atividades deste segmento."}},{"id":"tecnologia","es":{"n":"Innovación Tecnológica y Telecomunicaciones","t":"El Link entre el Derecho y el Desarrollo Tecnológico","s":"Contratos tech, riesgos de IA, licencias y defensa ante disputas regulatorias.","f":"Apoyamos a empresas especializadas en el área y startups en la redacción de contratos y acuerdos de servicios, así como en el análisis de riesgos legales asociados con nuevas tecnologías, incluyendo la inteligencia artificial. Prestamos apoyo en la obtención de licencias y la regulación de servicios, además de la defensa ante disputas regulatorias. A través de nuestra firma, cuentas con un respaldo legal confiable para impulsar el crecimiento y la sostenibilidad en el ámbito tecnológico."},"en":{"n":"Technology & Telecommunications","t":"The Link Between Law and Technological Development","s":"Tech contracts, AI risk, licensing and defense in regulatory disputes.","f":"We support companies specialized in the field and startups in drafting contracts and service agreements, as well as analyzing legal risks associated with new technologies, including artificial intelligence. We assist in obtaining licenses and service regulation, in addition to defense in regulatory disputes. Through our firm, you have reliable legal backing to drive growth and sustainability in the technology field."},"pt":{"n":"Inovação Tecnológica e Telecomunicações","t":"O Elo Entre o Direito e o Desenvolvimento Tecnológico","s":"Contratos de tecnologia, riscos de IA, licenciamento e defesa em disputas regulatórias.","f":"Apoiamos empresas especializadas na área e startups na redação de contratos e acordos de serviços, bem como na análise de riscos jurídicos associados a novas tecnologias, incluindo a inteligência artificial. Prestamos apoio na obtenção de licenças e na regulação de serviços, além da defesa em disputas regulatórias. Por meio de nosso escritório, você conta com um respaldo jurídico confiável para impulsionar o crescimento e a sustentabilidade no âmbito tecnológico."}},{"id":"fintech","es":{"n":"Financiero y Asesoría en Fintech","t":"Innovación para el Éxito Financiero","s":"Regulación bancaria, mercado de capitales y estructuración de plataformas de pago.","f":"Desde nuestra experiencia en el sector, prestamos asesoría experta en bancos, seguros y mercado de capitales, además de servicios de consultoría en fintech, ayudando a corporaciones y startups en el entorno regulatorio actual. La elaboración de contratos financieros, asesoría en la regulación de productos bancarios, gestión de riesgos y cumplimiento normativo forman parte de nuestro catálogo. Apoyamos en la implementación de tecnologías emergentes, obtención de licencias y estructuración legal de plataformas de pagos y financiamiento."},"en":{"n":"Financial & Fintech Advisory","t":"Innovation for Financial Success","s":"Banking regulation, capital markets and structuring of payment platforms.","f":"Drawing on our experience in the sector, we provide expert advisory to banks, insurers and capital markets, in addition to fintech consulting services, helping corporations and startups navigate today's regulatory environment. Drafting financial contracts, advisory on banking-product regulation, risk management and regulatory compliance are all part of our service catalog. We support the implementation of emerging technologies, the acquisition of licenses and the legal structuring of payment and financing platforms."},"pt":{"n":"Financeiro e Assessoria em Fintech","t":"Inovação para o Sucesso Financeiro","s":"Regulação bancária, mercado de capitais e estruturação de plataformas de pagamento.","f":"A partir de nossa experiência no setor, prestamos assessoria especializada a bancos, seguradoras e mercado de capitais, além de serviços de consultoria em fintech, ajudando corporações e startups no ambiente regulatório atual. A elaboração de contratos financeiros, assessoria na regulação de produtos bancários, gestão de riscos e cumprimento normativo fazem parte de nosso catálogo de serviços. Apoiamos a implementação de tecnologias emergentes, a obtenção de licenças e a estruturação jurídica de plataformas de pagamento e financiamento."}}];

var UI = {"es":{"locale":"es-VE","selectArea":"Selecciona un área","viewDetail":"Ver detalle","viewAllAreas":"Ver las 18 áreas de práctica →","risk":{"penal":{"tag":"Penal","title":"Te recomendamos nuestra área Penal","text":"Con base en tus respuestas, tu situación se beneficiaría de acompañamiento en Derecho Penal, con un enfoque preventivo, correctivo o estratégico según la etapa del proceso."},"civilfam":{"tag":"Civil / Familia","title":"Te recomendamos Civil, Familia o Inmobiliario","text":"Tu caso apunta a materia civil, familiar o inmobiliaria. Nuestro equipo puede ofrecerte una ruta clara y personalizada para resolverlo."},"laboral":{"tag":"Laboral / Tributario","title":"Te recomendamos Laboral, Tributario o Compliance","text":"Identificamos elementos propios de relaciones laborales, obligaciones fiscales o cumplimiento normativo. Podemos ayudarte a prevenir riesgos y resolver lo que ya está en curso."},"otro":{"tag":"Corporativo","title":"Te recomendamos una consulta general con Corporativo y Comercial","text":"Tu situación puede abarcar más de un área. Una primera consulta con nuestro equipo corporativo permitirá derivarte al especialista correcto."},"urgentNote":"Marcaste que necesitas orientación lo antes posible: prioriza agendar tu cita hoy mismo."},"chat":{"def":"Gracias por escribir. Un miembro de nuestro equipo continuará esta conversación en breve.","agendar":"Con gusto. Puedes completar el formulario en la sección \"Agendar Cita\" y elegir modalidad presencial o videollamada.","individual":"Perfecto. La asesoría individual está pensada para necesidades personales o familiares. ¿Deseas que agendemos una primera consulta?","corporativa":"Perfecto, te conectamos con el área Corporativo y Comercial. ¿Deseas que agendemos una primera consulta?","estado":"Para consultar el estado de tu caso, ingresa al Portal de Clientes con tu usuario asignado.","hello":"Hola. Soy el asistente virtual de VEXSTON. ¿En qué área legal necesitas orientación?"},"video":{"featuredTag":"Video destacado","viewBtn":"Ver en YouTube","watchFull":"Ver canal completo"},"abogados":{"listTitle":"Nuestro Equipo","listSubtitle":"Conoce a los abogados de VEXSTON.","cardCall":"Llamar al abogado","cardWhatsApp":"WhatsApp Oficina","cardOffice":"Llamar a la oficina","cardEmail":"Enviar correo","cardWeb":"Visitar página web","cardInstagram":"Instagram","cardMap":"Cómo llegar","infoTitle":"Información","personalEmail":"Correo personal","institutionalEmail":"Correo institucional","web":"Página web","saveContact":"Guardar contacto","saveNote":"Tus datos se guardan de forma segura en tu agenda de contactos.","back":"Volver al equipo","areas":"Áreas de práctica"}},"en":{"locale":"en-US","selectArea":"Select an area","viewDetail":"View details","viewAllAreas":"View all 18 practice areas →","risk":{"penal":{"tag":"Criminal","title":"We recommend our Criminal Law practice","text":"Based on your answers, your situation would benefit from Criminal Law support, with a preventive, corrective or strategic approach depending on the stage of the process."},"civilfam":{"tag":"Civil / Family","title":"We recommend Civil, Family or Real Estate","text":"Your case points to a civil, family or real-estate matter. Our team can offer you a clear, personalized path to resolve it."},"laboral":{"tag":"Labor / Tax","title":"We recommend Labor, Tax or Compliance","text":"We identified elements typical of labor relations, tax obligations or regulatory compliance. We can help you prevent risks and resolve what is already underway."},"otro":{"tag":"Corporate","title":"We recommend a general consultation with Corporate & Commercial","text":"Your situation may span more than one area. An initial consultation with our corporate team will route you to the right specialist."},"urgentNote":"You indicated you need guidance as soon as possible: make booking your appointment a priority today."},"chat":{"def":"Thanks for writing. A member of our team will continue this conversation shortly.","agendar":"Happy to help. You can fill out the form in the \"Book an Appointment\" section and choose in-person or video call.","individual":"Great. Individual advisory is designed for personal or family needs. Would you like us to schedule a first consultation?","corporativa":"Great, we'll connect you with our Corporate & Commercial area. Would you like us to schedule a first consultation?","estado":"To check your case status, log in to the Client Portal with your assigned username.","hello":"Hello. I am the VEXSTON virtual assistant. Which area of law do you need guidance on?"},"video":{"featuredTag":"Featured video","viewBtn":"Watch on YouTube","watchFull":"View the full channel"},"abogados":{"listTitle":"Our Team","listSubtitle":"Meet the attorneys at VEXSTON.","cardCall":"Call attorney","cardWhatsApp":"Office WhatsApp","cardOffice":"Call the office","cardEmail":"Send email","cardWeb":"Visit website","cardInstagram":"Instagram","cardMap":"Get directions","infoTitle":"Information","personalEmail":"Personal email","institutionalEmail":"Institutional email","web":"Website","saveContact":"Save contact","saveNote":"Your data is saved securely to your contacts.","back":"Back to team","areas":"Practice areas"}},"pt":{"locale":"pt-BR","selectArea":"Selecione uma área","viewDetail":"Ver detalhes","viewAllAreas":"Ver as 18 áreas de atuação →","risk":{"penal":{"tag":"Penal","title":"Recomendamos nossa área Penal","text":"Com base em suas respostas, sua situação se beneficiaria de acompanhamento em Direito Penal, com uma abordagem preventiva, corretiva ou estratégica conforme a etapa do processo."},"civilfam":{"tag":"Civil / Família","title":"Recomendamos Civil, Família ou Imobiliário","text":"Seu caso aponta para uma questão civil, familiar ou imobiliária. Nossa equipe pode oferecer um caminho claro e personalizado para resolvê-lo."},"laboral":{"tag":"Trabalhista / Tributário","title":"Recomendamos Trabalhista, Tributário ou Compliance","text":"Identificamos elementos próprios de relações trabalhistas, obrigações fiscais ou conformidade regulatória. Podemos ajudá-lo a prevenir riscos e resolver o que já está em curso."},"otro":{"tag":"Corporativo","title":"Recomendamos uma consulta geral com Corporativo e Comercial","text":"Sua situação pode abranger mais de uma área. Uma primeira consulta com nossa equipe corporativa permitirá encaminhá-lo ao especialista correto."},"urgentNote":"Você indicou que precisa de orientação o mais breve possível: priorize agendar sua consulta hoje mesmo."},"chat":{"def":"Obrigado por escrever. Um membro de nossa equipe continuará esta conversa em breve.","agendar":"Com prazer. Você pode preencher o formulário na seção \"Agendar Consulta\" e escolher a modalidade presencial ou videochamada.","individual":"Perfeito. A assessoria individual é pensada para necessidades pessoais ou familiares. Deseja que agendemos uma primeira consulta?","corporativa":"Perfeito, vamos conectá-lo com a área Corporativo e Comercial. Deseja que agendemos uma primeira consulta?","estado":"Para consultar o status do seu processo, acesse o Portal do Cliente com seu usuário atribuído.","hello":"Olá. Sou o assistente virtual da VEXSTON. Em que área jurídica precisa de orientação?"},"video":{"featuredTag":"Vídeo em destaque","viewBtn":"Assistir no YouTube","watchFull":"Ver canal completo"},"abogados":{"listTitle":"Nosso Time","listSubtitle":"Conheça os advogados da VEXSTON.","cardCall":"Ligar para o advogado","cardWhatsApp":"WhatsApp Escritório","cardOffice":"Ligar para o escritório","cardEmail":"Enviar e-mail","cardWeb":"Visitar site","cardInstagram":"Instagram","cardMap":"Como chegar","infoTitle":"Informações","personalEmail":"E-mail pessoal","institutionalEmail":"E-mail institucional","web":"Site","saveContact":"Salvar contato","saveNote":"Seus dados são salvos de forma segura na sua agenda de contatos.","back":"Voltar ao time","areas":"Áreas de atuação"}}};

var I18N = {
  es:{}, /* el HTML ya viene en español */
  en:{
    "sg.steps":"We understand. We anticipate. We act.",
    "sg.text":"The three bars that form the E in VEXSTON are the three steps by which we approach every matter, in that order and without skipping any. The method is in the name.",
    "cl.sign":"Law in Caracas. International judgement.",
    "cl.p2":"They require vision. They require strategy. They require knowing where we stand and where we intend to arrive.",
    "cl.p1":"VEXSTON accompanies decisions that require more than a legal answer.",
    "cl.title":"When the legal path is not obvious, judgement matters.",
    "vv.4d":"We practise law with integrity, responsibility and respect for its principles.",
    "vv.3d":"Behind every legal matter there is a person, a company or a project.",
    "vv.2d":"Technical depth is not negotiable.",
    "vv.1d":"Our clients' interests guide how we act.",
    "vv.p2":"Our practice is therefore built on four principles:",
    "vv.p1":"We believe legal practice demands far more than technical knowledge.",
    "vv.title":"How we practise law",
    "vv.eyebrow":"Principles",
    "me.3d":"We design and execute legal strategies aligned with our clients' objectives.",
    "me.3t":"We act",
    "me.2d":"We identify risks, scenarios and opportunities before they become irreversible decisions.",
    "me.2t":"We anticipate",
    "me.1d":"We analyse the legal, commercial and personal context behind each matter. Before answering, we listen.",
    "me.1t":"We understand",
    "me.sub":"At VEXSTON we examine each situation from a comprehensive perspective, turning legal problems into strategies for action.",
    "me.q":"What is at stake? What risks exist? What alternatives are available? Which path allows us to move forward with the greatest certainty?",
    "me.lead":"Every matter begins with a question.",
    "me.title":"From problem to strategy.",
    "me.eyebrow":"The method",
    "ap.title":"A firm built to navigate complexity.",
    "tools.d4":"Reference estimate of severance entitlement based on monthly salary and complete years of service.",
    "nav.inicio":"Home",
    "nav.equipo":"Our Team",
    "video.eyebrow":"Multimedia",
    "video.title":"VEXSTON on video.",
    "video.sub":"Analysis, interviews and legal content on our YouTube channel.",
    "video.cta":"View the full channel",
    "faq.eyebrow":"Frequently Asked Questions",
    "faq.title":"Answers to your legal questions in Caracas",
    "faq.sub":"The most frequent questions from our clients in Caracas about legal fees, court proceedings, practice areas and how to book a legal consultation.",
    "faq.cardTitle":"Can't find your answer?",
    "faq.cardText":"Briefly tell us about your case and our team will guide you with no obligation. Book a legal consultation via WhatsApp, video call or at our offices in Caracas.",
    "faq.cardBtn":"Book a consultation",
    "zonas.eyebrow":"Coverage Areas",
    "zonas.title":"Lawyers in the Caracas metropolitan area",
    "zonas.intro":"We handle consultations and legal procedures throughout Caracas and Miranda state: Chacao, Altamira, Los Palos Grandes, Campo Alegre, La Castellana, El Rosal, Las Mercedes and the east of the city.",
    "mg.f5":"Our Team",
    "mg.f5s":"Attorneys and specialists",
    "nav.firma":"The Firm",
    "nav.areasP":"Practice Areas",
    "nav.portalS":"Portal & Services",
    "nav.centroC":"Knowledge Centre",
    "nav.agendar":"Book a Meeting",
    "nav.ver18":"See all 18 practice areas",
    "cta.portal":"Client Portal",
    "mg.f1":"About Us",
    "mg.f1s":"Overview, mission and vision",
    "mg.f2":"Philosophy and Values",
    "mg.f2s":"Loyalty, excellence, empathy, justice",
    "mg.f3":"Our Offices",
    "mg.f3s":"Gallery · Ávila / Caracas",
    "mg.f4":"Commitment and Ethics",
    "mg.f4s":"Confidentiality and dedicated attention",
    "mg.p1":"Private Portal Access",
    "mg.p1s":"Client login · 2FA",
    "mg.p2":"Case Status Lookup",
    "mg.p2s":"Case file timeline",
    "mg.p3":"Procedural Deadline Calculator",
    "mg.p3s":"Terms and time limits",
    "mg.s0":"Online Services",
    "mg.s1":"Express Opinion Request",
    "mg.s1s":"Preliminary legal guidance",
    "mg.s2":"Payments / E-Invoicing",
    "mg.s2s":"Fee management",
    "mg.s3":"Court Calendar",
    "mg.s3s":"Hearings and sitting days",
    "mg.k0":"Legal Forum",
    "mg.k1":"Case Law and Index of Decisions",
    "mg.k2":"Digital Library and Bulletins",
    "mg.r0":"Resources",
    "mg.r1":"Opinion Pieces & Blog",
    "mg.r2":"Legal Calculators",
    "hs.1":"Years of combined experience",
    "hs.2":"Areas of specialisation",
    "hs.3":"Portal access around the clock",
    "areas.title":"18 practice areas, one firm.",
    "areas.sub":"Comprehensive counsel for individuals and companies in Caracas and its surroundings. Visit each speciality page to see the full detail.",
    "about.title":"VEXSTON, the firm redefining legal advisory in Caracas.",
    "about.p1":"Founded on a clear vision of excellence and commitment, our mission is to provide comprehensive, tailored legal solutions that answer our clients' specific needs. We combine an innovative approach with a solid legal structure to deliver exceptional service that does not merely meet expectations but exceeds them.",
    "about.p2":"Our lawyers bring together more than 100 years of combined experience across diverse areas of law. That breadth of practice lets us approach each matter with deep knowledge and effective problem-solving, ensuring every client receives meticulous, personalised and highly specialised service.",
    "val.1":"Loyalty",
    "val.2":"Excellence",
    "val.3":"Empathy",
    "val.4":"Justice",
    "mv.m":"Mission",
    "mv.mt":"To provide comprehensive legal counsel and effective defence to individuals and companies, both nationally and internationally. Our highly qualified team is devoted to protecting our clients' rights with passion, professionalism and unwavering commitment.",
    "mv.v":"Vision",
    "mv.vt":"To establish ourselves as an unquestioned benchmark for quality and excellence in defending our clients' interests, recognised internationally for our preventive advisory, dispute resolution and legal compliance services.",
    "risk.eyebrow":"Interactive widget",
    "risk.title":"Initial Legal Risk Assessment",
    "risk.sub":"Answer four short questions and we will point you to the practice area and the kind of support your situation calls for, before you book your consultation.",
    "risk.q":"Question",
    "risk.of":"of",
    "risk.restart":"Start over",
    "risk.q1":"Is your legal need personal or business-related?",
    "risk.q1a":"Personal / family",
    "risk.q1b":"Business / corporate",
    "risk.q1c":"Both",
    "risk.q2":"Which best describes your current situation?",
    "risk.q2a":"I want to prevent a dispute (review, contract, compliance)",
    "risk.q2b":"A dispute or proceeding is already under way",
    "risk.q2c":"It is an urgent situation",
    "risk.q3":"Does it involve any of these matters?",
    "risk.q3a":"Criminal / procedural",
    "risk.q3b":"Civil, family or real estate",
    "risk.q3c":"Labour, tax or compliance",
    "risk.q3d":"Other / not sure",
    "risk.q4":"How soon do you need guidance?",
    "risk.q4a":"As soon as possible",
    "risk.q4b":"This week",
    "risk.q4c":"I am exploring options",
    "pledge.eyebrow":"Commitment to clients",
    "pledge.title":"How we handle every case file",
    "pledge.t1":"Personalised, Dedicated Attention",
    "pledge.d1":"We understand that every client is unique. We focus on understanding your specific needs so we can deliver tailored legal solutions, with open communication and truthful, timely reporting at every stage of the process.",
    "pledge.t2":"Confidentiality and Ethics",
    "pledge.d2":"We guarantee absolute protection of all information provided to us. We act with the strictest integrity, honouring and preserving the trust placed in us in every interaction.",
    "portal.eyebrow":"Secure private area",
    "portal.title":"Client Portal",
    "portal.sub":"Your case file, your documents and your payments in one place, with the same dedication we bring to your matter offline.",
    "portal.b1":"Secure authentication with two-factor verification (2FA)",
    "portal.b2":"Encrypted document inbox",
    "portal.b3":"Visual timeline of your case progress",
    "portal.b4":"Automatic notifications by WhatsApp and email",
    "portal.enter":"Enter the portal",
    "portal.request":"Request access",
    "portal.tab1":"Case Status",
    "portal.tab2":"Express Opinion",
    "portal.tab3":"Payments",
    "portal.c1":"Company incorporation — FORUM C.A.",
    "portal.c2":"Corporate contract review",
    "portal.c3":"Individual employment advisory",
    "portal.s1":"In progress",
    "portal.s2":"Under review",
    "portal.s3":"Closed",
    "portal.t1":"Documentation received and validated",
    "portal.t2":"Instrument drafting under way",
    "portal.t3":"Final review and signature",
    "portal.next":"Next step",
    "portal.d1":"Briefly describe your query and receive preliminary legal guidance from our team.",
    "portal.locked":"Available with portal access",
    "portal.p1":"Fees — July 2026",
    "portal.p2":"Fees — June 2026",
    "portal.pend":"Pending",
    "portal.paid":"Paid",
    "portal.paylocked":"Pay online — available with access",
    "login.title":"Private access",
    "login.pass":"Password",
    "login.note":"This is a preview of the portal experience. Full authentication (2FA) goes live once the firm's backend is integrated.",
    "login.go":"Continue with 2FA verification",
    "login.alt":"Don't have access yet?",
    "login.ask":"Request it here →",
    "soon.title":"Coming soon",
    "soon.head":"We are preparing your online access",
    "soon.text":"The VEXSTON Client Portal will be available soon: case status, documents and payments in a private, secure space with two-factor authentication.",
    "soon.note":"Meanwhile, our team is at your service via WhatsApp, email or phone.",
    "soon.cta":"Contact the firm",
    "soon.ok":"Got it",
    "know.eyebrow":"Knowledge centre",
    "know.title":"The VEXSTON legal forum.",
    "know.t1":"Case Law",
    "know.d1":"Index of significant decisions from the Supreme Court of Justice and other bodies.",
    "know.t2":"Digital Library",
    "know.d2":"Bulletins and periodic publications from the firm for the profession.",
    "know.t3":"Opinion Pieces",
    "know.d3":"Analysis and commentary from our lawyers on current legal affairs.",
    "know.t4":"Legal Calculators",
    "know.d4":"Reference tools for common legal estimates.",
    "know.search":"Advanced legal search",
    "know.searchBtn":"Search",
    "know.recent":"Recent articles",
    "post.c1":"Corporate",
    "post.t1":"Good corporate governance: from formality to competitive advantage",
    "post.d1":"How a well-designed compliance programme protects and strengthens the company in Caracas.",
    "post.c2":"Labour",
    "post.t2":"What every company should review in its collective agreements",
    "post.d2":"Critical points in collective bargaining under the current framework.",
    "post.c3":"Tax",
    "post.t3":"Strategic tax planning for year-end",
    "post.d3":"Practical recommendations to optimise your company's tax burden.",
    "ant.eyebrow":"Legal calculator · Reference · Labour",
    "ant.title":"Severance Pay Estimator",
    "ant.sub":"Reference estimate of severance entitlement based on monthly salary and complete years of service.",
    "ant.salary":"Reference monthly salary (Bs.)",
    "ant.years":"Complete years of service",
    "ant.run":"Calculate estimate",
    "book.eyebrow":"Book an appointment",
    "book.info":"Contact information",
    "book.addr":"Chacao, Caracas — Miranda",
    "book.m1":"In person",
    "book.m1d":"Offices in Caracas",
    "book.m2":"Video call",
    "book.m2d":"Synced with your calendar",
    "book.m3":"Phone call",
    "book.m3d":"To a landline",
    "book.m4":"WhatsApp call",
    "book.m4d":"Fastest response",
    "form.name":"Full name",
    "form.mail":"Email address",
    "form.tel":"Phone",
    "form.area":"Practice area",
    "form.msg":"Tell us briefly about your case",
    "form.send":"Request appointment",
    "form.note":"You will receive confirmation and automatic reminders by WhatsApp and email before your appointment.",
    "chat.name":"VEXSTON Assistant",
    "chat.status":"Online · Replies 24/7",
    "chat.q1":"Book an appointment",
    "chat.q2":"Individual advisory",
    "chat.q3":"Corporate advisory",
    "chat.q4":"My case status","nav.areas":"Practice","nav.tools":"Tools","nav.office":"Offices","nav.book":"Book","nav.contact":"Contact",
    "hero.title":"Lawyers in <span class=\"accent\">Caracas</span>.",
    "hero.eyebrow":"Law firm in Caracas",
    "seo.eyebrow":"Law firm",
    "seo.title":"Lawyers in Caracas",
    "seo.p1":"VEXSTON is a law firm in Caracas providing personalized, specialized legal counsel. We bring together more than 100 years of combined experience and a team that handles personal and corporate matters across 18 practice areas.",
    "seo.p2":"If you are looking for lawyers in Caracas, VEXSTON is a legal office that combines deep knowledge, strategy and closeness: from criminal defense and labor law to corporate, real estate, tax and family counsel, with offices in Chacao and in-person or video consultations.",
    "seo.p3":"We serve the entire Caracas metropolitan area and Miranda state: Chacao, Altamira, Los Palos Grandes, La Castellana, El Rosal, Las Mercedes and the east of the city. Our specialties include criminal defense in Caracas, labor law in Caracas, corporate law and real estate law in Caracas.",
    "hero.sub":"Strategic firmness, loyalty and legal excellence.",
    "cta.book":"Book a consultation","cta.areas":"See practice areas","firm.title":"Where Caracas becomes <em>navigable</em>.",
    "firm.p1":"Some legal matters are resolved from a single provision. Others demand an understanding of the whole context: the legislation, the institutions, the procedures, the registries, the commercial reality and the particular circumstances of each client.",
    "firm.p2":"At VEXSTON we understand that a firm's value lies not only in knowing the law, but in knowing how to interpret it, how to apply it and how to turn it into a strategy capable of moving forward.",
    "firm.p3":"That is why we advise companies, business owners, investors and individuals on decisions that call for legal depth and strategic vision, within Venezuela and in matters connected to other jurisdictions. VEXSTON exists to make that complexity navigable.","firm.s2":"Languages of service","firm.s3":"Response to inquiries",
    "tools.eyebrow":"Tools","tools.title":"Open instruments for the bar",
    "tools.sub":"Free resources for lawyers, companies and citizens. These are working references, not opinions: applying them to a specific case always requires professional review.",
    "tools.t1":"Procedural Deadline Calculator","tools.d1":"Compute the expiry of a term in calendar or business days from a fixed date, with the corresponding caveat for court-session days.",
    "tools.t2":"Court Calendar","tools.d2":"Judicial recess dates, non-working days and court vacation periods that affect how your deadlines are counted.",
    "tools.t3":"Individual guidance","tools.d3":"Message us on WhatsApp for initial orientation on your matter before deciding whether to open a file with the firm.",
    "tools.use":"Open","tools.open":"View","tools.chat":"Message us",
    "calc.eyebrow":"Deadline computation","calc.from":"Start date","calc.type":"Type of term","calc.qty":"Number of days","calc.go":"Calculate",
    "calc.cont":"Calendar days","calc.hab":"Business days","calc.desp":"Court-session days",
    "office.title":"Our offices","office.sub":"Offices and meeting rooms in Chacao, Caracas. We receive clients by appointment and also meet by video call when the matter allows.",
    "book.title":"Book a consultation","book.sub":"Choose whichever channel suits you. We confirm within the same business day and send an automatic reminder 24 hours ahead.",
    "book.c1":"In person","book.c1d":"At our Chacao offices, by appointment.",
    "book.c2":"Video call","book.c2d":"Remote meeting for clients in and outside the country.",
    "book.c3":"Landline","book.c3d":"Call us during office hours, Monday to Friday.",
    "book.c4":"WhatsApp","book.c4d":"Direct call or message with our intake team.",
    "foot.blurb":"Law firm based in Caracas with reach across the Caracas metropolitan area. Comprehensive counsel for individuals and companies in 18 practice areas, from criminal, civil and family matters to corporate, tax, labour, real estate, energy, agrarian and technology law.",
    "foot.contact":"Contact","foot.nav":"Navigation","foot.addr":"Chacao, Caracas — Miranda",
    "foot.rights":"All rights reserved.","foot.disclaimer":"Content on this site is informational and does not constitute legal advice.",
    "court.eyebrow":"Court calendar","court.title":"Dates that affect computation",
    "court.note":"General reference. Each judicial circuit publishes its own calendar and courts may declare additional non-session days. Always verify with the court hearing your case."
  },
  pt:{
    "sg.steps":"Entendemos. Antecipamos. Atuamos.",
    "sg.text":"As três barras que formam o E de VEXSTON são os três passos com que abordamos cada assunto, por essa ordem e sem saltarmos nenhum. O método está no nome.",
    "cl.sign":"Direito em Caracas. Critério internacional.",
    "cl.p2":"Exigem visão. Exigem estratégia. Exigem saber onde estamos e para onde queremos chegar.",
    "cl.p1":"A VEXSTON acompanha decisões que exigem mais do que uma resposta legal.",
    "cl.title":"Quando o caminho jurídico não é evidente, o critério importa.",
    "vv.4d":"Exercemos o Direito com integridade, responsabilidade e respeito pelos seus princípios.",
    "vv.3d":"Por detrás de cada assunto jurídico existe uma pessoa, uma empresa ou um projeto.",
    "vv.2d":"A profundidade técnica não é negociável.",
    "vv.1d":"Os interesses dos nossos clientes orientam a nossa atuação.",
    "vv.p2":"Por isso a nossa prática constrói-se sobre quatro princípios:",
    "vv.p1":"Acreditamos que a prática jurídica exige muito mais do que conhecimento técnico.",
    "vv.title":"A nossa forma de exercer o Direito",
    "vv.eyebrow":"Princípios",
    "me.3d":"Desenhamos e executamos estratégias jurídicas alinhadas com os objetivos dos nossos clientes.",
    "me.3t":"Atuamos",
    "me.2d":"Identificamos riscos, cenários e oportunidades antes que se convertam em decisões irreversíveis.",
    "me.2t":"Antecipamos",
    "me.1d":"Analisamos o contexto jurídico, empresarial e pessoal por detrás de cada assunto. Antes de responder, escutamos.",
    "me.1t":"Entendemos",
    "me.sub":"Na VEXSTON analisamos cada situação numa perspetiva integral, para transformar problemas jurídicos em estratégias de ação.",
    "me.q":"O que está em jogo? Que riscos existem? Que alternativas são possíveis? Que caminho permite avançar com maior segurança?",
    "me.lead":"Cada assunto começa com uma pergunta.",
    "me.title":"Do problema à estratégia.",
    "me.eyebrow":"O método",
    "ap.title":"Uma firma para transitar o complexo.",
    "tools.d4":"Estimativa referencial da prestação de antiguidade a partir do salário mensal e dos anos completos de serviço.",
    "nav.inicio":"Início",
    "nav.equipo":"Nossa Equipe",
    "video.eyebrow":"Multimídia",
    "video.title":"VEXSTON em vídeo.",
    "video.sub":"Análises, entrevistas e conteúdo jurídico no nosso canal do YouTube.",
    "video.cta":"Ver canal completo",
    "faq.eyebrow":"Perguntas Frequentes",
    "faq.title":"Respostas às suas dúvidas jurídicas em Caracas",
    "faq.sub":"As perguntas mais frequentes dos nossos clientes em Caracas sobre honorários de advogados, processos judiciais, áreas de atuação e como agendar uma consulta jurídica.",
    "faq.cardTitle":"Não encontrou sua resposta?",
    "faq.cardText":"Conte-nos brevemente o seu caso e a nossa equipe orientará você sem compromisso. Agende uma consulta jurídica por WhatsApp, videochamada ou nos nossos escritórios em Caracas.",
    "faq.cardBtn":"Agendar consulta",
    "zonas.eyebrow":"Zonas de Atendimento",
    "zonas.title":"Advogados na região metropolitana de Caracas",
    "zonas.intro":"Atendemos consultas e trâmites jurídicos em toda Caracas e no estado Miranda: Chacao, Altamira, Los Palos Grandes, Campo Alegre, La Castellana, El Rosal, Las Mercedes e o leste da cidade.",
    "mg.f5":"Nossa Equipe",
    "mg.f5s":"Advogados e especialistas",
    "nav.firma":"A Firma",
    "nav.areasP":"Áreas de Atuação",
    "nav.portalS":"Portal e Serviços",
    "nav.centroC":"Centro de Conhecimento",
    "nav.agendar":"Marcar Consulta",
    "nav.ver18":"Ver as 18 áreas de atuação",
    "cta.portal":"Portal Clientes",
    "mg.f1":"Sobre Nós",
    "mg.f1s":"Apresentação, missão e visão",
    "mg.f2":"Filosofia e Valores",
    "mg.f2s":"Lealdade, excelência, empatia, justiça",
    "mg.f3":"Instalações",
    "mg.f3s":"Galeria · Ávila / Caracas",
    "mg.f4":"Compromisso e Ética",
    "mg.f4s":"Confidencialidade e atenção dedicada",
    "mg.p1":"Acesso ao Portal Privado",
    "mg.p1s":"Login de clientes · 2FA",
    "mg.p2":"Consulta do Estado dos Processos",
    "mg.p2s":"Linha do tempo do processo",
    "mg.p3":"Calculadora de Prazos Processuais",
    "mg.p3s":"Cálculo de termos e prazos",
    "mg.s0":"Serviços em Linha",
    "mg.s1":"Pedido de Parecer Expresso",
    "mg.s1s":"Resposta jurídica preliminar",
    "mg.s2":"Pagamentos / Faturação Eletrónica",
    "mg.s2s":"Gestão de honorários",
    "mg.s3":"Calendário Judicial",
    "mg.s3s":"Audiências e dias de expediente",
    "mg.k0":"Foro Jurídico",
    "mg.k1":"Jurisprudência e Índice de Decisões",
    "mg.k2":"Biblioteca Digital e Boletins",
    "mg.r0":"Recursos",
    "mg.r1":"Artigos de Opinião & Blog",
    "mg.r2":"Calculadoras Jurídicas",
    "hs.1":"Anos de experiência combinada",
    "hs.2":"Áreas de especialização",
    "hs.3":"Atendimento pelo portal 24/7",
    "areas.title":"18 áreas de atuação, uma só firma.",
    "areas.sub":"Assessoria integral a pessoas singulares e coletivas em Caracas e arredores. Visite a página de cada especialidade para ver o detalhe completo.",
    "about.title":"VEXSTON, a firma que redefine a assessoria jurídica em Caracas.",
    "about.p1":"Fundada com uma visão clara de excelência e compromisso, a nossa missão é proporcionar soluções jurídicas integrais e personalizadas que respondam às necessidades específicas dos nossos clientes. Combinamos uma abordagem inovadora com uma sólida estrutura jurídica para oferecer um serviço excecional que não apenas cumpre, mas supera as expectativas.",
    "about.p2":"Contamos com uma equipa de advogados que em conjunto soma mais de 100 anos de experiência em diversas áreas do direito. Essa ampla trajetória permite-nos abordar cada caso com profundo conhecimento e capacidade de resolução efetiva, assegurando que cada cliente receba um serviço meticuloso, personalizado e altamente especializado.",
    "val.1":"Lealdade",
    "val.2":"Excelência",
    "val.3":"Empatia",
    "val.4":"Justiça",
    "mv.m":"Missão",
    "mv.mt":"Prestar assessoria jurídica integral e defesa efetiva a pessoas singulares e coletivas, tanto a nível nacional como internacional. A nossa equipa altamente qualificada dedica-se a proteger os direitos dos nossos clientes com paixão, profissionalismo e um compromisso inabalável.",
    "mv.v":"Visão",
    "mv.vt":"Consolidarmo-nos como uma referência indiscutível em qualidade e excelência na defesa dos interesses dos nossos clientes, reconhecidos internacionalmente pelos nossos serviços de assessoria preventiva, resolução de conflitos e conformidade legal.",
    "risk.eyebrow":"Widget interativo",
    "risk.title":"Avaliador de Risco Jurídico Inicial",
    "risk.sub":"Responda a quatro perguntas breves e orientamo-lo sobre a área de atuação e o tipo de acompanhamento que a sua situação exige, antes de marcar a sua consulta.",
    "risk.q":"Pergunta",
    "risk.of":"de",
    "risk.restart":"Começar de novo",
    "risk.q1":"A sua necessidade jurídica é de carácter pessoal ou empresarial?",
    "risk.q1a":"Pessoal / familiar",
    "risk.q1b":"Empresarial / corporativa",
    "risk.q1c":"Ambas",
    "risk.q2":"O que descreve melhor a sua situação atual?",
    "risk.q2a":"Quero prevenir um conflito (revisão, contrato, conformidade)",
    "risk.q2b":"Já existe um conflito ou processo em curso",
    "risk.q2c":"É uma situação urgente",
    "risk.q3":"Envolve alguma destas matérias?",
    "risk.q3a":"Penal / processual",
    "risk.q3b":"Civil, família ou imobiliário",
    "risk.q3c":"Laboral, tributário ou compliance",
    "risk.q3d":"Outra / não tenho a certeza",
    "risk.q4":"Em quanto tempo precisa de orientação?",
    "risk.q4a":"O mais depressa possível",
    "risk.q4b":"Esta semana",
    "risk.q4c":"Estou a explorar opções",
    "pledge.eyebrow":"Compromisso com os clientes",
    "pledge.title":"Como trabalhamos cada processo",
    "pledge.t1":"Atenção Personalizada e Dedicada",
    "pledge.d1":"Entendemos que cada cliente é único. Focamo-nos em compreender as suas necessidades específicas para facilitar soluções jurídicas à medida, com comunicação aberta e relatórios verídicos e oportunos em cada etapa do processo.",
    "pledge.t2":"Confidencialidade e Ética",
    "pledge.d2":"Garantimos a proteção absoluta de toda a informação que nos é fornecida. Agimos com a mais estrita integridade, respeitando e mantendo a confiança que nos foi depositada em cada interação.",
    "portal.eyebrow":"Área privada segura",
    "portal.title":"Portal de Clientes",
    "portal.sub":"O seu processo, os seus documentos e os seus pagamentos num só lugar, com a mesma dedicação com que tratamos o seu caso fora de linha.",
    "portal.b1":"Autenticação segura com verificação em dois passos (2FA)",
    "portal.b2":"Caixa de documentos cifrada",
    "portal.b3":"Linha do tempo visual do progresso do seu processo",
    "portal.b4":"Notificações automáticas por WhatsApp e correio",
    "portal.enter":"Entrar no portal",
    "portal.request":"Solicitar acesso",
    "portal.tab1":"Estado dos Processos",
    "portal.tab2":"Parecer Expresso",
    "portal.tab3":"Pagamentos",
    "portal.c1":"Constituição de sociedade — FORUM C.A.",
    "portal.c2":"Revisão contratual corporativa",
    "portal.c3":"Assessoria laboral individual",
    "portal.s1":"Em curso",
    "portal.s2":"Em revisão",
    "portal.s3":"Encerrado",
    "portal.t1":"Documentação recebida e validada",
    "portal.t2":"Redação do instrumento em curso",
    "portal.t3":"Revisão final e assinatura",
    "portal.next":"Próximo passo",
    "portal.d1":"Descreva brevemente a sua consulta e receba uma orientação jurídica preliminar da nossa equipa.",
    "portal.locked":"Disponível com acesso ao portal",
    "portal.p1":"Honorários — julho 2026",
    "portal.p2":"Honorários — junho 2026",
    "portal.pend":"Pendente",
    "portal.paid":"Pago",
    "portal.paylocked":"Pagar em linha — disponível com acesso",
    "login.title":"Acesso privado",
    "login.pass":"Palavra-passe",
    "login.note":"Esta é uma antevisão da experiência do portal. A autenticação completa (2FA) é ativada assim que o backend da firma estiver integrado.",
    "login.go":"Continuar com verificação 2FA",
    "login.alt":"Ainda não tem acesso?",
    "login.ask":"Solicite-o aqui →",
    "soon.title":"Disponível em breve",
    "soon.head":"Estamos a preparar o seu acesso em linha",
    "soon.text":"O Portal de Clientes da VEXSTON estará disponível em breve: consulta do estado dos seus processos, documentos e pagamentos num espaço privado e seguro, com autenticação de dois fatores.",
    "soon.note":"Entretanto, a nossa equipa está ao seu dispor por WhatsApp, correio ou telefone.",
    "soon.cta":"Contactar o escritório",
    "soon.ok":"Entendido",
    "know.eyebrow":"Centro de conhecimento",
    "know.title":"O foro jurídico da VEXSTON.",
    "know.t1":"Jurisprudência",
    "know.d1":"Índice de decisões relevantes do Supremo Tribunal de Justiça e de outros órgãos.",
    "know.t2":"Biblioteca Digital",
    "know.d2":"Boletins e publicações periódicas da firma para o foro.",
    "know.t3":"Artigos de Opinião",
    "know.d3":"Análises e comentários dos nossos advogados sobre a atualidade jurídica.",
    "know.t4":"Calculadoras Jurídicas",
    "know.d4":"Ferramentas referenciais para estimativas jurídicas comuns.",
    "know.search":"Buscador jurídico avançado",
    "know.searchBtn":"Pesquisar",
    "know.recent":"Artigos recentes",
    "post.c1":"Corporativo",
    "post.t1":"Boa governança corporativa: da formalidade à vantagem competitiva",
    "post.d1":"Como um programa de compliance bem desenhado protege e capitaliza a empresa em Caracas.",
    "post.c2":"Laboral",
    "post.t2":"O que toda a empresa deve rever nos seus contratos coletivos",
    "post.d2":"Pontos críticos na negociação coletiva no quadro vigente.",
    "post.c3":"Tributário",
    "post.t3":"Planeamento fiscal estratégico para o fecho do ano",
    "post.d3":"Recomendações práticas para otimizar a carga fiscal da sua empresa.",
    "ant.eyebrow":"Calculadora jurídica · Referencial · Laboral",
    "ant.title":"Estimador de Antiguidade Laboral",
    "ant.sub":"Estimativa referencial da prestação de antiguidade a partir do salário mensal e dos anos completos de serviço.",
    "ant.salary":"Salário mensal de referência (Bs.)",
    "ant.years":"Anos completos de serviço",
    "ant.run":"Calcular estimativa",
    "book.eyebrow":"Marcar consulta",
    "book.info":"Informação de contacto",
    "book.addr":"Chacao, Caracas — Miranda",
    "book.m1":"Presencial",
    "book.m1d":"Escritórios em Caracas",
    "book.m2":"Videochamada",
    "book.m2d":"Sincronizada com o seu calendário",
    "book.m3":"Chamada telefónica",
    "book.m3d":"Para telefone fixo",
    "book.m4":"Chamada por WhatsApp",
    "book.m4d":"Resposta mais rápida",
    "form.name":"Nome completo",
    "form.mail":"Correio eletrónico",
    "form.tel":"Telefone",
    "form.area":"Área de atuação",
    "form.msg":"Conte-nos brevemente o seu caso",
    "form.send":"Solicitar marcação",
    "form.note":"Receberá confirmação e lembretes automáticos por WhatsApp e correio eletrónico antes da sua consulta.",
    "chat.name":"Assistente VEXSTON",
    "chat.status":"Em linha · Responde 24/7",
    "chat.q1":"Marcar consulta",
    "chat.q2":"Assessoria individual",
    "chat.q3":"Assessoria corporativa",
    "chat.q4":"Estado do meu processo","nav.areas":"Áreas","nav.tools":"Ferramentas","nav.office":"Instalações","nav.book":"Agendar","nav.contact":"Contacto",
    "hero.title":"Advogados em <span class=\"accent\">Caracas</span>.",
    "hero.eyebrow":"Escritório de advogados em Caracas",
    "seo.eyebrow":"Escritório de advogados",
    "seo.title":"Advogados em Caracas",
    "seo.p1":"A VEXSTON é um escritório de advogados em Caracas com atendimento personalizado e especializado. Contamos com mais de 100 anos de experiência combinada e uma equipe que atende assuntos pessoais e empresariais em 18 áreas de atuação.",
    "seo.p2":"Se procura advogados em Caracas, encontrará na VEXSTON um escritório jurídico que combina conhecimento profundo, estratégia e proximidade: desde defesa penal e direito trabalhista até assessoria corporativa, imobiliária, tributária e de família, com escritórios em Chacao e atendimento presencial ou por videochamada.",
    "seo.p3":"Atendemos consultas em toda a região metropolitana de Caracas e no estado Miranda: Chacao, Altamira, Los Palos Grandes, La Castellana, El Rosal, Las Mercedes e o leste da cidade. Entre as nossas especialidades estão o advogado criminalista em Caracas, o advogado trabalhista em Caracas, o advogado corporativo e o advogado imobiliário em Caracas.",
    "hero.sub":"Firmeza estratégica, lealdade e excelência jurídica.",
    "cta.book":"Agendar consulta","cta.areas":"Ver áreas de atuação","firm.title":"Onde a Venezuela se torna <em>navegável</em>.",
    "firm.p1":"Há assuntos jurídicos que se resolvem a partir de uma norma. Outros exigem compreender o contexto completo: a legislação, as instituições, os procedimentos, os registos, a realidade empresarial e as circunstâncias particulares de cada cliente.",
    "firm.p2":"Na VEXSTON entendemos que o valor de uma firma não está apenas em conhecer a lei, mas em saber como interpretá-la, como aplicá-la e como convertê-la numa estratégia capaz de avançar.",
    "firm.p3":"Por isso acompanhamos empresas, empresários, investidores e particulares em decisões que exigem profundidade jurídica e visão estratégica, tanto dentro da Venezuela como em assuntos ligados a outras jurisdições. A VEXSTON existe para tornar transitável essa complexidade.","firm.s2":"Idiomas de atendimento","firm.s3":"Resposta a consultas",
    "tools.eyebrow":"Ferramentas","tools.title":"Instrumentos abertos para o foro",
    "tools.sub":"Recursos de uso livre para advogados, empresas e cidadãos. São referências de trabalho, não pareceres: a aplicação a um caso concreto exige sempre revisão profissional.",
    "tools.t1":"Calculadora de Prazos Processuais","tools.d1":"Calcule o vencimento de um prazo em dias corridos ou úteis a partir de uma data certa, com a advertência correspondente aos dias de expediente.",
    "tools.t2":"Calendário Judicial","tools.d2":"Datas de recesso judicial, dias não úteis e períodos de férias forenses que incidem no cômputo dos seus prazos.",
    "tools.t3":"Orientação individual","tools.d3":"Escreva-nos pelo WhatsApp e receba uma orientação inicial sobre o seu assunto antes de decidir abrir um processo com a firma.",
    "tools.use":"Usar","tools.open":"Consultar","tools.chat":"Escrever",
    "calc.eyebrow":"Cômputo de prazos","calc.from":"Data de início","calc.type":"Tipo de prazo","calc.qty":"Quantidade de dias","calc.go":"Calcular",
    "calc.cont":"Dias corridos","calc.hab":"Dias úteis","calc.desp":"Dias de expediente",
    "office.title":"As nossas instalações","office.sub":"Escritórios e salas de reunião em Chacao, Caracas. Recebemos clientes com marcação prévia e também por videochamada quando o assunto o permite.",
    "book.title":"Agendar uma consulta","book.sub":"Escolha a via que lhe for mais cómoda. Confirmamos no mesmo dia útil e enviamos um lembrete automático 24 horas antes.",
    "book.c1":"Presencial","book.c1d":"Nos nossos escritórios em Chacao, com marcação prévia.",
    "book.c2":"Videochamada","book.c2d":"Reunião remota para clientes dentro e fora do país.",
    "book.c3":"Telefone fixo","book.c3d":"Ligue-nos em horário de expediente, de segunda a sexta.",
    "book.c4":"WhatsApp","book.c4d":"Chamada ou mensagem direta com a equipa de atendimento.",
    "foot.blurb":"Firma jurídica sediada em Caracas com alcance na região metropolitana de Caracas. Assessoria integral a pessoas singulares e coletivas em 18 áreas de atuação, do penal, civil e da família ao societário, tributário, laboral, imobiliário, energético, agrário e tecnológico.",
    "foot.contact":"Contacto","foot.nav":"Navegação","foot.addr":"Chacao, Caracas — Miranda",
    "foot.rights":"Todos os direitos reservados.","foot.disclaimer":"O conteúdo deste site é informativo e não constitui assessoria jurídica.",
    "court.eyebrow":"Calendário judicial","court.title":"Datas que afetam o cômputo",
    "court.note":"Referência geral. Cada circuito judicial publica o seu próprio calendário e os tribunais podem declarar dias adicionais sem expediente. Verifique sempre no tribunal da causa."
  }
};

var LANG = "es";


var COURT = [
  ["15 ago — 15 sep","Receso judicial (vacaciones tribunalicias)","Judicial recess (court vacation)","Recesso judicial (férias forenses)"],
  ["24 dic — 6 ene","Receso de fin de año","Year-end recess","Recesso de fim de ano"],
  ["Semana Santa","Jueves y Viernes Santo","Holy Thursday and Good Friday","Quinta e Sexta-feira Santa"],
  ["1 de mayo","Día del Trabajador","Labor Day","Dia do Trabalhador"],
  ["Carnaval","Lunes y martes de Carnaval","Carnival Monday and Tuesday","Segunda e terça de Carnaval"]
];

var FMT = {es:"es-VE",en:"en-US",pt:"pt-PT"};

var CTXT = {
  es:{
    cont:"días continuos",hab:"días hábiles",desp:"días de despacho",
    vence:"El lapso vence el",
    nc:"Cómputo en días continuos: se cuentan todos los días del calendario, incluidos sábados, domingos y feriados. El día de inicio no se cuenta.",
    nh:"Cómputo en días hábiles: se excluyen sábados y domingos. No se descuentan feriados nacionales ni días declarados no laborables, que debe verificar aparte.",
    nd:"Los días de despacho no pueden calcularse automáticamente: dependen del calendario del tribunal de la causa y solo constan en el Libro Diario. Esta fecha es una referencia en días hábiles, no un cómputo procesal válido.",
    warn:"Verifique siempre el cómputo con el tribunal. Esta herramienta es orientativa y no sustituye la revisión del expediente.",
    err:"Indique una fecha de inicio y una cantidad de días válida.",
    antErr:"Indique un salario y una cantidad de años válidos.",
    antNote:"Estimación referencial por {y} año(s) de servicio, calculada a razón de 30 días de salario por año, tomando el salario diario como el mensual dividido entre 30.",
    antWarn:"Herramienta meramente referencial e ilustrativa. No considera bonificaciones, salario integral, intereses ni el cálculo alternativo previsto en la ley. No constituye asesoría legal ni sustituye la evaluación de su caso por nuestro equipo.",
    juri:"El buscador jurídico se activa junto con el Portal de Clientes. Mientras tanto, escríbanos y le hacemos llegar lo que encontremos sobre «{q}».",
    formErr:"Indique al menos su nombre y su correo electrónico.",
    formOk:"Gracias, {n}. Hemos registrado su solicitud de cita {m}. Le confirmaremos por correo dentro del mismo día hábil.",
    loginSoon:"El acceso con verificación en dos pasos se activará una vez integrado el backend de la firma. Si ya es cliente, escríbanos y le damos sus credenciales.",
    loginErr:"Indique su correo electrónico para continuar."
  },
  en:{
    cont:"calendar days",hab:"business days",desp:"court-session days",
    vence:"The term expires on",
    nc:"Calendar-day count: every day is counted, including weekends and holidays. The start date is not counted.",
    nh:"Business-day count: Saturdays and Sundays are excluded. National holidays and declared non-working days are not deducted and must be checked separately.",
    nd:"Court-session days cannot be computed automatically: they depend on the calendar of the court hearing the case and appear only in its daily record. This date is a business-day reference, not a valid procedural computation.",
    warn:"Always verify the computation with the court. This tool is indicative and does not replace review of the case file.",
    err:"Enter a valid start date and number of days.",
    antErr:"Enter a valid salary and number of years.",
    antNote:"Reference estimate for {y} year(s) of service, calculated at 30 days of salary per year, taking the daily wage as the monthly figure divided by 30.",
    antWarn:"Purely indicative and illustrative tool. It does not account for bonuses, integral salary, interest or the alternative calculation set out in the statute. It is not legal advice and does not replace review of your case by our team.",
    juri:"The legal search engine goes live alongside the Client Portal. In the meantime, write to us and we will send you what we find on \\u201c{q}\\u201d.",
    formErr:"Please enter at least your name and email address.",
    formOk:"Thank you, {n}. Your {m} appointment request has been registered. We will confirm by email within the same business day.",
    loginSoon:"Two-factor access goes live once the firm's backend is integrated. If you are already a client, write to us and we will issue your credentials.",
    loginErr:"Enter your email address to continue."
  },
  pt:{
    cont:"dias corridos",hab:"dias úteis",desp:"dias de expediente",
    vence:"O prazo vence a",
    nc:"Contagem em dias corridos: contam-se todos os dias do calendário, incluindo fins de semana e feriados. O dia de início não se conta.",
    nh:"Contagem em dias úteis: excluem-se sábados e domingos. Não se descontam feriados nacionais nem dias declarados não úteis, que deve verificar à parte.",
    nd:"Os dias de expediente não podem ser calculados automaticamente: dependem do calendário do tribunal da causa e constam apenas no seu livro diário. Esta data é uma referência em dias úteis, não um cômputo processual válido.",
    warn:"Verifique sempre o cômputo com o tribunal. Esta ferramenta é orientativa e não substitui a revisão do processo.",
    err:"Indique uma data de início e uma quantidade de dias válida.",
    antErr:"Indique um salário e uma quantidade de anos válidos.",
    antNote:"Estimativa referencial por {y} ano(s) de serviço, calculada à razão de 30 dias de salário por ano, tomando o salário diário como o mensal dividido por 30.",
    antWarn:"Ferramenta meramente referencial e ilustrativa. Não considera bonificações, salário integral, juros nem o cálculo alternativo previsto na lei. Não constitui assessoria jurídica nem substitui a avaliação do seu caso pela nossa equipa.",
    juri:"O buscador jurídico é ativado juntamente com o Portal de Clientes. Entretanto, escreva-nos e enviamos-lhe o que encontrarmos sobre \\u201c{q}\\u201d.",
    formErr:"Indique pelo menos o seu nome e o seu correio eletrónico.",
    formOk:"Obrigado, {n}. Registámos o seu pedido de marcação {m}. Confirmaremos por correio no mesmo dia útil.",
    loginSoon:"O acesso com verificação em dois passos será ativado assim que o backend da firma estiver integrado. Se já é cliente, escreva-nos e enviamos as suas credenciais.",
    loginErr:"Indique o seu correio eletrónico para continuar."
  }
};

/* ============================= VIDEOS / YOUTUBE ============================= */
var VIDEOS_ES = [
  {id:'HnvfOXTQgiI', featured:true, tag:'Familia', title:'Episodio 6. Ejercicio Unilateral de la Patria Potestad', desc:'Análisis de la patria potestad ejercida por uno solo de los progenitores: requisitos legales y su impacto en la vida del niño o adolescente.'},
  {id:'g4QQNmpKIY8', tag:'Constitucional', title:'2da Temporada - Episodio 5. Avocamiento', desc:'Qué es el avocamiento, cuándo procede y cómo el Tribunal Supremo de Justicia lo utiliza para asumir causas.'},
  {id:'VysHfvrPRI8', tag:'Tecnología', title:'2da Temporada - Episodio 4. Ciberseguridad', desc:'Riesgos digitales, protección de datos y las herramientas legales para defenderte frente a delitos cibernéticos.'},
  {id:'CDfU5O4L0G0', tag:'Tecnología', title:'2da Temporada - Episodio 3. Evidencias Digitales', desc:'Valor probatorio de mensajes, correos y registros digitales dentro de un proceso judicial en Venezuela.'},
  {id:'2XeX5aj6Wes', tag:'Inmobiliario', title:'Edición Especial Derecho con Propósito - ¿Desalojo o invasión?', desc:'Diferencias entre desalojo e invasión, las vías legales y cómo actuar frente a la ocupación de un inmueble.'},
  {id:'B9icsl_jikk', tag:'Internacional', title:'Episodio 3. Ejecución de sentencias extranjeras en Venezuela', desc:'Cómo se ejecutan en Venezuela las sentencias dictadas en el extranjero: exequátur y requisitos de reconocimiento.'},
  {id:'pQGcDMfaQ6U', tag:'Laboral', title:'¿Estás preparado para afrontar una demanda laboral?', desc:'Pasos prácticos para preparar tu defensa ante una demanda laboral y proteger tus derechos como empleador.'}
];
var VIDEOS_EN_RAW = [
  {id:'HnvfOXTQgiI', featured:true, tag:'Family', title:'Episodio 6. Ejercicio Unilateral de la Patria Potestad', desc:'An analysis of parental authority exercised by a single parent: legal requirements and its impact on the life of the child or adolescent.'},
  {id:'g4QQNmpKIY8', tag:'Constitutional', title:'2da Temporada - Episodio 5. Avocamiento', desc:'What avocamiento is, when it applies and how the Supreme Court of Justice uses it to take over cases.'},
  {id:'VysHfvrPRI8', tag:'Technology', title:'2da Temporada - Episodio 4. Ciberseguridad', desc:'Digital risks, data protection and the legal tools to defend yourself against cybercrime.'},
  {id:'CDfU5O4L0G0', tag:'Technology', title:'2da Temporada - Episodio 3. Evidencias Digitales', desc:'The evidentiary value of messages, emails and digital records in a judicial proceeding in Venezuela.'},
  {id:'2XeX5aj6Wes', tag:'Real Estate', title:'Edición Especial Derecho con Propósito - ¿Desalojo o invasión?', desc:'Differences between eviction and invasion, the legal routes and how to act when a property is occupied.'},
  {id:'B9icsl_jikk', tag:'International', title:'Episodio 3. Ejecución de sentencias extranjeras en Venezuela', desc:'How judgments rendered abroad are enforced in Venezuela: exequatur and recognition requirements.'},
  {id:'pQGcDMfaQ6U', tag:'Labor', title:'¿Estás preparado para afrontar una demanda laboral?', desc:'Practical steps to prepare your defense against a labor claim and protect your rights as an employer.'}
];
var VIDEOS_PT_RAW = [
  {id:'HnvfOXTQgiI', featured:true, tag:'Família', title:'Episodio 6. Ejercicio Unilateral de la Patria Potestad', desc:'Análise do poder parental exercido por apenas um dos progenitores: requisitos legais e seu impacto na vida da criança ou do adolescente.'},
  {id:'g4QQNmpKIY8', tag:'Constitucional', title:'2da Temporada - Episodio 5. Avocamiento', desc:'O que é o avocamento, quando ele ocorre e como o Supremo Tribunal o utiliza para assumir processos.'},
  {id:'VysHfvrPRI8', tag:'Tecnologia', title:'2da Temporada - Episodio 4. Ciberseguridad', desc:'Riscos digitais, proteção de dados e as ferramentas legais para se defender de crimes cibernéticos.'},
  {id:'CDfU5O4L0G0', tag:'Tecnologia', title:'2da Temporada - Episodio 3. Evidencias Digitales', desc:'Valor probatório de mensagens, e-mails e registros digitais em um processo judicial na Venezuela.'},
  {id:'2XeX5aj6Wes', tag:'Imobiliário', title:'Edición Especial Derecho con Propósito - ¿Desalojo ou invasión?', desc:'Diferenças entre despejo e invasão, as vias legais e como agir diante da ocupação de um imóvel.'},
  {id:'B9icsl_jikk', tag:'Internacional', title:'Episodio 3. Ejecución de sentencias extranjeras en Venezuela', desc:'Como as sentenças estrangeiras são executadas na Venezuela: exequátur e requisitos de reconhecimento.'},
  {id:'pQGcDMfaQ6U', tag:'Trabalhista', title:'¿Estás preparado para afrontar una demanda laboral?', desc:'Passos práticos para preparar sua defesa em uma ação trabalhista e proteger seus direitos como empregador.'}
];
var VIDEOS_I18N = { es: VIDEOS_ES, en: VIDEOS_EN_RAW, pt: VIDEOS_PT_RAW };
function getVideos(){ return VIDEOS_I18N[LANG] || VIDEOS_ES; }
var YT_CHANNEL_ID = 'UCZgpumlYClYA-rfrKp5QS6g';
var YT_CHANNEL_URL = 'https://www.youtube.com/@Attornialex';
var YT_RSS_PROXY = '';
async function fetchChannelVideos(){
  var rss = 'https://www.youtube.com/feeds/videos.xml?channel_id=' + YT_CHANNEL_ID;
  var url = YT_RSS_PROXY ? YT_RSS_PROXY + encodeURIComponent(rss) : rss;
  var resp = await fetch(url);
  if(!resp.ok) throw new Error('RSS no disponible');
  var doc = new DOMParser().parseFromString(await resp.text(), 'text/xml');
  var entries = [].slice.call(doc.querySelectorAll('entry'));
  if(!entries.length) throw new Error('Sin entradas');
  return entries.slice(0, 7).map(function(e){
    var id = (e.querySelector('videoId')||{}).textContent || '';
    return {
      id: id,
      title: (e.querySelector('title')||{}).textContent || '',
      desc: (e.querySelector('group description')||{}).textContent || '',
      tag: (e.querySelector('group category[label]')||{}).getAttribute ? e.querySelector('group category[label]').getAttribute('label') || '' : '',
      featured: false
    };
  });
}

/* ============================= ABOGADOS ============================= */
var ABOGADOS = [
  {
    id:'domingo-ramirez',
    nombre:'Domingo A. Ramírez Quintero',
    cargo:'Abogado',
    telPersonal:'+584241689854',
    telPersonalFmt:'(+58) 424-1689854',
    telOficina:'+582129527991',
    telOficinaFmt:'(+58) 212-9527991',
    whatsapp:'+584126173777',
    whatsappFmt:'(+58) 412-6173777',
    emailPersonal:'daramirez@vexston.com',
    emailInstitucional:'contacto@vexston.com',
    web:'https://www.vexston.com',
    instagram:'https://instagram.com/vexston',
    instagramHandle:'@vexston',
    areas:['Corporativo y Comercial','Derecho Civil','Derecho Laboral']
  },
  {
    id:'imperio-salazar',
    nombre:'Imperio Y. Salazar Yépez',
    cargo:'Abogada laboral y civil',
    telPersonal:'+584142051806',
    telPersonalFmt:'(+58) 414-2051806',
    telOficina:'+582129527991',
    telOficinaFmt:'(+58) 212-9527991',
    whatsapp:'+584126173777',
    whatsappFmt:'(+58) 412-6173777',
    emailPersonal:'contacto@vexston.com',
    emailInstitucional:'contacto@vexston.com',
    web:'https://www.vexston.com',
    instagram:'https://instagram.com/vexston',
    instagramHandle:'@vexston',
    areas:['Derecho Laboral','Derecho Civil']
  },
  {
    id:'rafael-gil',
    nombre:'Rafael R. Gil Valderrama',
    cargo:'Abogado laboral, civil y mercantil',
    telPersonal:'+584143312085',
    telPersonalFmt:'(+58) 414-3312085',
    telOficina:'+582129527991',
    telOficinaFmt:'(+58) 212-9527991',
    whatsapp:'+584126173777',
    whatsappFmt:'(+58) 412-6173777',
    emailPersonal:'contacto@vexston.com',
    emailInstitucional:'contacto@vexston.com',
    web:'https://www.vexston.com',
    instagram:'https://instagram.com/vexston',
    instagramHandle:'@vexston',
    areas:['Derecho Laboral','Derecho Civil','Derecho Mercantil']
  }
];
function getAbogado(id){ return ABOGADOS.find(function(a){ return a.id === id; }); }
function getAbogados(){ return ABOGADOS; }
